# Generated by Django 3.2.7 on 2021-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follower_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='imageurl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
