# Generated by Django 3.2.7 on 2021-09-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='network.Posts'),
        ),
    ]
