# Generated by Django 3.2.7 on 2021-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210928_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likecount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
