# Generated by Django 3.2.7 on 2021-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_posts_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
