# Generated by Django 3.2.7 on 2021-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_posts_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likecount',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
