# Generated by Django 3.2.7 on 2021-10-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_posts_likecount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='datetime',
        ),
    ]
