# Generated by Django 3.2.7 on 2021-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20211001_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
