# Generated by Django 3.2.7 on 2021-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_profile_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_posts',
            field=models.ManyToManyField(related_name='user_posts', to='network.Posts'),
        ),
    ]
