# Generated by Django 3.2.7 on 2021-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20211001_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='profile',
            name='imageurl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
